package de.greenrobot.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CITY".
 */
public class City extends BaseDao implements java.io.Serializable {

    private long id;
//    /** Not-null value. */
//    private String name;
//    /** Not-null value. */
//    private String pinyinName;

    public City() {
    }

    public City(long id) {
        this.id = id;
    }

    public City(long id, String name, String pinyinName) {
        this.id = id;
        this.name = name;
        this.pinyinName = pinyinName;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPinyinName() {
        return pinyinName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPinyinName(String pinyinName) {
        this.pinyinName = pinyinName;
    }

}
