package de.greenrobot.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import de.greenrobot.dao.IndicatorDao;
import de.greenrobot.dao.InspectionDao;
import de.greenrobot.dao.InterpretationDao;
import de.greenrobot.dao.TumorDao;
import de.greenrobot.dao.MedicineDao;
import de.greenrobot.dao.CityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        IndicatorDao.createTable(db, ifNotExists);
        InspectionDao.createTable(db, ifNotExists);
        InterpretationDao.createTable(db, ifNotExists);
        TumorDao.createTable(db, ifNotExists);
        MedicineDao.createTable(db, ifNotExists);
        CityDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        IndicatorDao.dropTable(db, ifExists);
        InspectionDao.dropTable(db, ifExists);
        InterpretationDao.dropTable(db, ifExists);
        TumorDao.dropTable(db, ifExists);
        MedicineDao.dropTable(db, ifExists);
        CityDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(IndicatorDao.class);
        registerDaoClass(InspectionDao.class);
        registerDaoClass(InterpretationDao.class);
        registerDaoClass(TumorDao.class);
        registerDaoClass(MedicineDao.class);
        registerDaoClass(CityDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
