package de.greenrobot.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INDICATOR".
 */
public class Indicator extends BaseDao implements java.io.Serializable {

    private long id;
    private Long updateTime;
    private Integer status;
//    private String name;
//    private String pinyinName;
    private String pinyinFullName;
    private String unit;
    private String fullName;
    private Boolean isActive;
    private Boolean isLandmark;

    public Indicator() {
    }

    public Indicator(long id) {
        this.id = id;
    }

    public Indicator(long id, Long updateTime, Integer status, String name, String pinyinName, String pinyinFullName, String unit, String fullName, Boolean isActive, Boolean isLandmark) {
        this.id = id;
        this.updateTime = updateTime;
        this.status = status;
        this.name = name;
        this.pinyinName = pinyinName;
        this.pinyinFullName = pinyinFullName;
        this.unit = unit;
        this.fullName = fullName;
        this.isActive = isActive;
        this.isLandmark = isLandmark;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPinyinName() {
        return pinyinName;
    }

    public void setPinyinName(String pinyinName) {
        this.pinyinName = pinyinName;
    }

    public String getPinyinFullName() {
        return pinyinFullName;
    }

    public void setPinyinFullName(String pinyinFullName) {
        this.pinyinFullName = pinyinFullName;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    public Boolean getIsLandmark() {
        return isLandmark;
    }

    public void setIsLandmark(Boolean isLandmark) {
        this.isLandmark = isLandmark;
    }

}
