package de.greenrobot.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.dao.Inspection;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INSPECTION".
*/
public class InspectionDao extends AbstractDao<Inspection, Long> {

    public static final String TABLENAME = "INSPECTION";

    /**
     * Properties of entity Inspection.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "ID");
        public final static Property UpdateTime = new Property(1, Long.class, "updateTime", false, "UPDATE_TIME");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property PinyinName = new Property(3, String.class, "pinyinName", false, "PINYIN_NAME");
        public final static Property PinyinFullName = new Property(4, String.class, "pinyinFullName", false, "PINYIN_FULL_NAME");
        public final static Property FullName = new Property(5, String.class, "fullName", false, "FULL_NAME");
        public final static Property Status = new Property(6, Integer.class, "status", false, "STATUS");
        public final static Property IsActive = new Property(7, Boolean.class, "isActive", false, "IS_ACTIVE");
        public final static Property Insurance = new Property(8, Boolean.class, "insurance", false, "INSURANCE");
    };


    public InspectionDao(DaoConfig config) {
        super(config);
    }
    
    public InspectionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INSPECTION\" (" + //
                "\"ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"UPDATE_TIME\" INTEGER," + // 1: updateTime
                "\"NAME\" TEXT," + // 2: name
                "\"PINYIN_NAME\" TEXT," + // 3: pinyinName
                "\"PINYIN_FULL_NAME\" TEXT," + // 4: pinyinFullName
                "\"FULL_NAME\" TEXT," + // 5: fullName
                "\"STATUS\" INTEGER," + // 6: status
                "\"IS_ACTIVE\" INTEGER," + // 7: isActive
                "\"INSURANCE\" INTEGER);"); // 8: insurance
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INSPECTION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Inspection entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        Long updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(2, updateTime);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String pinyinName = entity.getPinyinName();
        if (pinyinName != null) {
            stmt.bindString(4, pinyinName);
        }
 
        String pinyinFullName = entity.getPinyinFullName();
        if (pinyinFullName != null) {
            stmt.bindString(5, pinyinFullName);
        }
 
        String fullName = entity.getFullName();
        if (fullName != null) {
            stmt.bindString(6, fullName);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(7, status);
        }
 
        Boolean isActive = entity.getIsActive();
        if (isActive != null) {
            stmt.bindLong(8, isActive ? 1L: 0L);
        }
 
        Boolean insurance = entity.getInsurance();
        if (insurance != null) {
            stmt.bindLong(9, insurance ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Inspection readEntity(Cursor cursor, int offset) {
        Inspection entity = new Inspection( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // updateTime
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // pinyinName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // pinyinFullName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // fullName
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // status
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // isActive
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0 // insurance
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Inspection entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setUpdateTime(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPinyinName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPinyinFullName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFullName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStatus(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setIsActive(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setInsurance(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Inspection entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Inspection entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
