package de.greenrobot.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INTERPRETATION".
 */
public class Interpretation extends BaseDao implements java.io.Serializable {

    private long interpretationId;
//    private String name;
//    private String pinyinName;
    private Boolean isActive;

    public Interpretation() {
    }

    public Interpretation(long interpretationId) {
        this.interpretationId = interpretationId;
    }

    public Interpretation(long interpretationId, String name, String pinyinName, Boolean isActive) {
        this.interpretationId = interpretationId;
        this.name = name;
        this.pinyinName = pinyinName;
        this.isActive = isActive;
    }

    public long getInterpretationId() {
        return interpretationId;
    }

    public void setInterpretationId(long interpretationId) {
        this.interpretationId = interpretationId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPinyinName() {
        return pinyinName;
    }

    public void setPinyinName(String pinyinName) {
        this.pinyinName = pinyinName;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
