package de.greenrobot.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.dao.Interpretation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INTERPRETATION".
*/
public class InterpretationDao extends AbstractDao<Interpretation, Long> {

    public static final String TABLENAME = "INTERPRETATION";

    /**
     * Properties of entity Interpretation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property InterpretationId = new Property(0, long.class, "interpretationId", true, "INTERPRETATION_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property PinyinName = new Property(2, String.class, "pinyinName", false, "PINYIN_NAME");
        public final static Property IsActive = new Property(3, Boolean.class, "isActive", false, "IS_ACTIVE");
    };


    public InterpretationDao(DaoConfig config) {
        super(config);
    }
    
    public InterpretationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INTERPRETATION\" (" + //
                "\"INTERPRETATION_ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: interpretationId
                "\"NAME\" TEXT," + // 1: name
                "\"PINYIN_NAME\" TEXT," + // 2: pinyinName
                "\"IS_ACTIVE\" INTEGER);"); // 3: isActive
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INTERPRETATION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Interpretation entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getInterpretationId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String pinyinName = entity.getPinyinName();
        if (pinyinName != null) {
            stmt.bindString(3, pinyinName);
        }
 
        Boolean isActive = entity.getIsActive();
        if (isActive != null) {
            stmt.bindLong(4, isActive ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Interpretation readEntity(Cursor cursor, int offset) {
        Interpretation entity = new Interpretation( //
            cursor.getLong(offset + 0), // interpretationId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pinyinName
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // isActive
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Interpretation entity, int offset) {
        entity.setInterpretationId(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPinyinName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsActive(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Interpretation entity, long rowId) {
        entity.setInterpretationId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Interpretation entity) {
        if(entity != null) {
            return entity.getInterpretationId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
