package de.greenrobot.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MEDICINE".
 */
public class Medicine implements java.io.Serializable {

    private long medicineId;
    private Long updateTime;
    private Long chemicalId;
    private Integer insurance;
    private Integer classify;
    private Integer imports;
    private Integer type;
    private Integer special;
    private Integer prescription;
    private Integer status;
    private String showName;
    private String chemicalName;
    private String medicineName;
    private String pinyinName;
    private String priceMax;
    private String priceMin;
    private boolean isActive;

    public Medicine() {
    }

    public Medicine(long medicineId) {
        this.medicineId = medicineId;
    }

    public Medicine(long medicineId, Long updateTime, Long chemicalId, Integer insurance, Integer classify, Integer imports, Integer type, Integer special, Integer prescription, Integer status, String showName, String chemicalName, String medicineName, String pinyinName, String priceMax, String priceMin, boolean isActive) {
        this.medicineId = medicineId;
        this.updateTime = updateTime;
        this.chemicalId = chemicalId;
        this.insurance = insurance;
        this.classify = classify;
        this.imports = imports;
        this.type = type;
        this.special = special;
        this.prescription = prescription;
        this.status = status;
        this.showName = showName;
        this.chemicalName = chemicalName;
        this.medicineName = medicineName;
        this.pinyinName = pinyinName;
        this.priceMax = priceMax;
        this.priceMin = priceMin;
        this.isActive = isActive;
    }

    public long getMedicineId() {
        return medicineId;
    }

    public void setMedicineId(long medicineId) {
        this.medicineId = medicineId;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public Long getChemicalId() {
        return chemicalId;
    }

    public void setChemicalId(Long chemicalId) {
        this.chemicalId = chemicalId;
    }

    public Integer getInsurance() {
        return insurance;
    }

    public void setInsurance(Integer insurance) {
        this.insurance = insurance;
    }

    public Integer getClassify() {
        return classify;
    }

    public void setClassify(Integer classify) {
        this.classify = classify;
    }

    public Integer getImports() {
        return imports;
    }

    public void setImports(Integer imports) {
        this.imports = imports;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getSpecial() {
        return special;
    }

    public void setSpecial(Integer special) {
        this.special = special;
    }

    public Integer getPrescription() {
        return prescription;
    }

    public void setPrescription(Integer prescription) {
        this.prescription = prescription;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getShowName() {
        return showName;
    }

    public void setShowName(String showName) {
        this.showName = showName;
    }

    public String getChemicalName() {
        return chemicalName;
    }

    public void setChemicalName(String chemicalName) {
        this.chemicalName = chemicalName;
    }

    public String getMedicineName() {
        return medicineName;
    }

    public void setMedicineName(String medicineName) {
        this.medicineName = medicineName;
    }

    public String getPinyinName() {
        return pinyinName;
    }

    public void setPinyinName(String pinyinName) {
        this.pinyinName = pinyinName;
    }

    public String getPriceMax() {
        return priceMax;
    }

    public void setPriceMax(String priceMax) {
        this.priceMax = priceMax;
    }

    public String getPriceMin() {
        return priceMin;
    }

    public void setPriceMin(String priceMin) {
        this.priceMin = priceMin;
    }

    public boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

}
