package de.greenrobot.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TUMOR".
 */
public class Tumor extends BaseDao implements java.io.Serializable {

    private long id;
//    private String name;
//    private String pinyinName;
    private Integer status;
    private Boolean isActive;

    public Tumor() {
    }

    public Tumor(long id) {
        this.id = id;
    }

    public Tumor(long id, String name, String pinyinName, Integer status, Boolean isActive) {
        this.id = id;
        this.name = name;
        this.pinyinName = pinyinName;
        this.status = status;
        this.isActive = isActive;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPinyinName() {
        return pinyinName;
    }

    public void setPinyinName(String pinyinName) {
        this.pinyinName = pinyinName;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
