package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ATTENTION_NOTICES".
 */
public class AttentionNotices implements java.io.Serializable {

    private long id;
    private String patientId;
    private String content;
    private Long time;
    private Long createTime;
    private Integer status;
    private Boolean isActive;

    public AttentionNotices() {
    }

    public AttentionNotices(long id) {
        this.id = id;
    }

    public AttentionNotices(long id, String patientId, String content, Long time, Long createTime, Integer status, Boolean isActive) {
        this.id = id;
        this.patientId = patientId;
        this.content = content;
        this.time = time;
        this.createTime = createTime;
        this.status = status;
        this.isActive = isActive;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
