package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHEMOTHERAPY_COURSE_MEDICINE".
 */
public class ChemotherapyCourseMedicine implements java.io.Serializable {

    private Long id;
    private Long medicineId;
    private Long chemotherapyCourseId;
    private String medicineName;

    public ChemotherapyCourseMedicine() {
    }

    public ChemotherapyCourseMedicine(Long id) {
        this.id = id;
    }

    public ChemotherapyCourseMedicine(Long id, Long medicineId, Long chemotherapyCourseId, String medicineName) {
        this.id = id;
        this.medicineId = medicineId;
        this.chemotherapyCourseId = chemotherapyCourseId;
        this.medicineName = medicineName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMedicineId() {
        return medicineId;
    }

    public void setMedicineId(Long medicineId) {
        this.medicineId = medicineId;
    }

    public Long getChemotherapyCourseId() {
        return chemotherapyCourseId;
    }

    public void setChemotherapyCourseId(Long chemotherapyCourseId) {
        this.chemotherapyCourseId = chemotherapyCourseId;
    }

    public String getMedicineName() {
        return medicineName;
    }

    public void setMedicineName(String medicineName) {
        this.medicineName = medicineName;
    }

}
