package de.greenrobot.dao.attention;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.dao.attention.ChemotherapyMedicine;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHEMOTHERAPY_MEDICINE".
*/
public class ChemotherapyMedicineDao extends AbstractDao<ChemotherapyMedicine, Long> {

    public static final String TABLENAME = "CHEMOTHERAPY_MEDICINE";

    /**
     * Properties of entity ChemotherapyMedicine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MedicineId = new Property(1, Long.class, "medicineId", false, "MEDICINE_ID");
        public final static Property ChemotherapyId = new Property(2, Long.class, "chemotherapyId", false, "CHEMOTHERAPY_ID");
        public final static Property MedicineName = new Property(3, String.class, "medicineName", false, "MEDICINE_NAME");
        public final static Property ChemicalName = new Property(4, String.class, "chemicalName", false, "CHEMICAL_NAME");
        public final static Property ShowName = new Property(5, String.class, "showName", false, "SHOW_NAME");
    };


    public ChemotherapyMedicineDao(DaoConfig config) {
        super(config);
    }
    
    public ChemotherapyMedicineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHEMOTHERAPY_MEDICINE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MEDICINE_ID\" INTEGER," + // 1: medicineId
                "\"CHEMOTHERAPY_ID\" INTEGER," + // 2: chemotherapyId
                "\"MEDICINE_NAME\" TEXT," + // 3: medicineName
                "\"CHEMICAL_NAME\" TEXT," + // 4: chemicalName
                "\"SHOW_NAME\" TEXT);"); // 5: showName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHEMOTHERAPY_MEDICINE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ChemotherapyMedicine entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long medicineId = entity.getMedicineId();
        if (medicineId != null) {
            stmt.bindLong(2, medicineId);
        }
 
        Long chemotherapyId = entity.getChemotherapyId();
        if (chemotherapyId != null) {
            stmt.bindLong(3, chemotherapyId);
        }
 
        String medicineName = entity.getMedicineName();
        if (medicineName != null) {
            stmt.bindString(4, medicineName);
        }
 
        String chemicalName = entity.getChemicalName();
        if (chemicalName != null) {
            stmt.bindString(5, chemicalName);
        }
 
        String showName = entity.getShowName();
        if (showName != null) {
            stmt.bindString(6, showName);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ChemotherapyMedicine readEntity(Cursor cursor, int offset) {
        ChemotherapyMedicine entity = new ChemotherapyMedicine( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // medicineId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // chemotherapyId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // medicineName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // chemicalName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // showName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ChemotherapyMedicine entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMedicineId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setChemotherapyId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setMedicineName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setChemicalName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setShowName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ChemotherapyMedicine entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ChemotherapyMedicine entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
