package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHEMOTHERAPY_COURSE".
 */
public class ChemotherapyCourse implements java.io.Serializable {

    private long id;
    private Long chemotherapyRecordId;
    private Long startTime;
    private Long endTime;
    private Integer endReason;
    private Integer status;
    private Integer times;
    private String description;
    private String patientId;
    private Boolean isActive;

    public ChemotherapyCourse() {
    }

    public ChemotherapyCourse(long id) {
        this.id = id;
    }

    public ChemotherapyCourse(long id, Long chemotherapyRecordId, Long startTime, Long endTime, Integer endReason, Integer status, Integer times, String description, String patientId, Boolean isActive) {
        this.id = id;
        this.chemotherapyRecordId = chemotherapyRecordId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.endReason = endReason;
        this.status = status;
        this.times = times;
        this.description = description;
        this.patientId = patientId;
        this.isActive = isActive;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getChemotherapyRecordId() {
        return chemotherapyRecordId;
    }

    public void setChemotherapyRecordId(Long chemotherapyRecordId) {
        this.chemotherapyRecordId = chemotherapyRecordId;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Integer getEndReason() {
        return endReason;
    }

    public void setEndReason(Integer endReason) {
        this.endReason = endReason;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getTimes() {
        return times;
    }

    public void setTimes(Integer times) {
        this.times = times;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
