package de.greenrobot.dao.attention;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.dao.attention.RecordIndex;
import de.greenrobot.dao.attention.RecordIndexItem;
import de.greenrobot.dao.attention.MedicineRecord;
import de.greenrobot.dao.attention.AssistMedicineRecord;
import de.greenrobot.dao.attention.SurgeryRecord;
import de.greenrobot.dao.attention.SurgeryMethods;
import de.greenrobot.dao.attention.Hospitalized;
import de.greenrobot.dao.attention.Radiotherapy;
import de.greenrobot.dao.attention.Chemotherapy;
import de.greenrobot.dao.attention.ChemotherapyMedicine;
import de.greenrobot.dao.attention.Patient;
import de.greenrobot.dao.attention.AttentionNotices;

import de.greenrobot.dao.attention.RecordIndexDao;
import de.greenrobot.dao.attention.RecordIndexItemDao;
import de.greenrobot.dao.attention.MedicineRecordDao;
import de.greenrobot.dao.attention.AssistMedicineRecordDao;
import de.greenrobot.dao.attention.SurgeryRecordDao;
import de.greenrobot.dao.attention.SurgeryMethodsDao;
import de.greenrobot.dao.attention.HospitalizedDao;
import de.greenrobot.dao.attention.RadiotherapyDao;
import de.greenrobot.dao.attention.ChemotherapyDao;
import de.greenrobot.dao.attention.ChemotherapyMedicineDao;
import de.greenrobot.dao.attention.PatientDao;
import de.greenrobot.dao.attention.AttentionNoticesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordIndexDaoConfig;
    private final DaoConfig recordIndexItemDaoConfig;
    private final DaoConfig medicineRecordDaoConfig;
    private final DaoConfig assistMedicineRecordDaoConfig;
    private final DaoConfig surgeryRecordDaoConfig;
    private final DaoConfig surgeryMethodsDaoConfig;
    private final DaoConfig hospitalizedDaoConfig;
    private final DaoConfig radiotherapyDaoConfig;
    private final DaoConfig chemotherapyDaoConfig;
    private final DaoConfig chemotherapyMedicineDaoConfig;
    private final DaoConfig patientDaoConfig;
    private final DaoConfig attentionNoticesDaoConfig;

    private final RecordIndexDao recordIndexDao;
    private final RecordIndexItemDao recordIndexItemDao;
    private final MedicineRecordDao medicineRecordDao;
    private final AssistMedicineRecordDao assistMedicineRecordDao;
    private final SurgeryRecordDao surgeryRecordDao;
    private final SurgeryMethodsDao surgeryMethodsDao;
    private final HospitalizedDao hospitalizedDao;
    private final RadiotherapyDao radiotherapyDao;
    private final ChemotherapyDao chemotherapyDao;
    private final ChemotherapyMedicineDao chemotherapyMedicineDao;
    private final PatientDao patientDao;
    private final AttentionNoticesDao attentionNoticesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordIndexDaoConfig = daoConfigMap.get(RecordIndexDao.class).clone();
        recordIndexDaoConfig.initIdentityScope(type);

        recordIndexItemDaoConfig = daoConfigMap.get(RecordIndexItemDao.class).clone();
        recordIndexItemDaoConfig.initIdentityScope(type);

        medicineRecordDaoConfig = daoConfigMap.get(MedicineRecordDao.class).clone();
        medicineRecordDaoConfig.initIdentityScope(type);

        assistMedicineRecordDaoConfig = daoConfigMap.get(AssistMedicineRecordDao.class).clone();
        assistMedicineRecordDaoConfig.initIdentityScope(type);

        surgeryRecordDaoConfig = daoConfigMap.get(SurgeryRecordDao.class).clone();
        surgeryRecordDaoConfig.initIdentityScope(type);

        surgeryMethodsDaoConfig = daoConfigMap.get(SurgeryMethodsDao.class).clone();
        surgeryMethodsDaoConfig.initIdentityScope(type);

        hospitalizedDaoConfig = daoConfigMap.get(HospitalizedDao.class).clone();
        hospitalizedDaoConfig.initIdentityScope(type);

        radiotherapyDaoConfig = daoConfigMap.get(RadiotherapyDao.class).clone();
        radiotherapyDaoConfig.initIdentityScope(type);

        chemotherapyDaoConfig = daoConfigMap.get(ChemotherapyDao.class).clone();
        chemotherapyDaoConfig.initIdentityScope(type);

        chemotherapyMedicineDaoConfig = daoConfigMap.get(ChemotherapyMedicineDao.class).clone();
        chemotherapyMedicineDaoConfig.initIdentityScope(type);

        patientDaoConfig = daoConfigMap.get(PatientDao.class).clone();
        patientDaoConfig.initIdentityScope(type);

        attentionNoticesDaoConfig = daoConfigMap.get(AttentionNoticesDao.class).clone();
        attentionNoticesDaoConfig.initIdentityScope(type);

        recordIndexDao = new RecordIndexDao(recordIndexDaoConfig, this);
        recordIndexItemDao = new RecordIndexItemDao(recordIndexItemDaoConfig, this);
        medicineRecordDao = new MedicineRecordDao(medicineRecordDaoConfig, this);
        assistMedicineRecordDao = new AssistMedicineRecordDao(assistMedicineRecordDaoConfig, this);
        surgeryRecordDao = new SurgeryRecordDao(surgeryRecordDaoConfig, this);
        surgeryMethodsDao = new SurgeryMethodsDao(surgeryMethodsDaoConfig, this);
        hospitalizedDao = new HospitalizedDao(hospitalizedDaoConfig, this);
        radiotherapyDao = new RadiotherapyDao(radiotherapyDaoConfig, this);
        chemotherapyDao = new ChemotherapyDao(chemotherapyDaoConfig, this);
        chemotherapyMedicineDao = new ChemotherapyMedicineDao(chemotherapyMedicineDaoConfig, this);
        patientDao = new PatientDao(patientDaoConfig, this);
        attentionNoticesDao = new AttentionNoticesDao(attentionNoticesDaoConfig, this);

        registerDao(RecordIndex.class, recordIndexDao);
        registerDao(RecordIndexItem.class, recordIndexItemDao);
        registerDao(MedicineRecord.class, medicineRecordDao);
        registerDao(AssistMedicineRecord.class, assistMedicineRecordDao);
        registerDao(SurgeryRecord.class, surgeryRecordDao);
        registerDao(SurgeryMethods.class, surgeryMethodsDao);
        registerDao(Hospitalized.class, hospitalizedDao);
        registerDao(Radiotherapy.class, radiotherapyDao);
        registerDao(Chemotherapy.class, chemotherapyDao);
        registerDao(ChemotherapyMedicine.class, chemotherapyMedicineDao);
        registerDao(Patient.class, patientDao);
        registerDao(AttentionNotices.class, attentionNoticesDao);
    }
    
    public void clear() {
        recordIndexDaoConfig.getIdentityScope().clear();
        recordIndexItemDaoConfig.getIdentityScope().clear();
        medicineRecordDaoConfig.getIdentityScope().clear();
        assistMedicineRecordDaoConfig.getIdentityScope().clear();
        surgeryRecordDaoConfig.getIdentityScope().clear();
        surgeryMethodsDaoConfig.getIdentityScope().clear();
        hospitalizedDaoConfig.getIdentityScope().clear();
        radiotherapyDaoConfig.getIdentityScope().clear();
        chemotherapyDaoConfig.getIdentityScope().clear();
        chemotherapyMedicineDaoConfig.getIdentityScope().clear();
        patientDaoConfig.getIdentityScope().clear();
        attentionNoticesDaoConfig.getIdentityScope().clear();
    }

    public RecordIndexDao getRecordIndexDao() {
        return recordIndexDao;
    }

    public RecordIndexItemDao getRecordIndexItemDao() {
        return recordIndexItemDao;
    }

    public MedicineRecordDao getMedicineRecordDao() {
        return medicineRecordDao;
    }

    public AssistMedicineRecordDao getAssistMedicineRecordDao() {
        return assistMedicineRecordDao;
    }

    public SurgeryRecordDao getSurgeryRecordDao() {
        return surgeryRecordDao;
    }

    public SurgeryMethodsDao getSurgeryMethodsDao() {
        return surgeryMethodsDao;
    }

    public HospitalizedDao getHospitalizedDao() {
        return hospitalizedDao;
    }

    public RadiotherapyDao getRadiotherapyDao() {
        return radiotherapyDao;
    }

    public ChemotherapyDao getChemotherapyDao() {
        return chemotherapyDao;
    }

    public ChemotherapyMedicineDao getChemotherapyMedicineDao() {
        return chemotherapyMedicineDao;
    }

    public PatientDao getPatientDao() {
        return patientDao;
    }

    public AttentionNoticesDao getAttentionNoticesDao() {
        return attentionNoticesDao;
    }

}
