package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HOSPITALIZED".
 */
public class Hospitalized implements java.io.Serializable {

    private long id;
    private long inTime;
    private int type;
    private Integer status;
    private String dayCount;
    /** Not-null value. */
    private String patientId;
    private String description;
    private String hospitalName;
    private long hospitalId;
    private String doctorName;
    private boolean isActive;

    public Hospitalized() {
    }

    public Hospitalized(long id) {
        this.id = id;
    }

    public Hospitalized(long id, long inTime, int type, Integer status, String dayCount, String patientId, String description, String hospitalName, long hospitalId, String doctorName, boolean isActive) {
        this.id = id;
        this.inTime = inTime;
        this.type = type;
        this.status = status;
        this.dayCount = dayCount;
        this.patientId = patientId;
        this.description = description;
        this.hospitalName = hospitalName;
        this.hospitalId = hospitalId;
        this.doctorName = doctorName;
        this.isActive = isActive;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getInTime() {
        return inTime;
    }

    public void setInTime(long inTime) {
        this.inTime = inTime;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getDayCount() {
        return dayCount;
    }

    public void setDayCount(String dayCount) {
        this.dayCount = dayCount;
    }

    /** Not-null value. */
    public String getPatientId() {
        return patientId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getHospitalName() {
        return hospitalName;
    }

    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    public long getHospitalId() {
        return hospitalId;
    }

    public void setHospitalId(long hospitalId) {
        this.hospitalId = hospitalId;
    }

    public String getDoctorName() {
        return doctorName;
    }

    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    public boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

}
