package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MARKER".
 */
public class Marker {

    private long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String recordName;

    public Marker() {
    }

    public Marker(long id) {
        this.id = id;
    }

    public Marker(long id, String name, String recordName) {
        this.id = id;
        this.name = name;
        this.recordName = recordName;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getRecordName() {
        return recordName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecordName(String recordName) {
        this.recordName = recordName;
    }

}
