package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RADIOTHERAPY_SUSPENDED_RECORDS".
 */
public class RadiotherapySuspendedRecords implements java.io.Serializable {

    private long id;
    private Long radiotherapyRecordId;
    private Long startTime;
    private Integer suspendDays;
    private Integer reason;
    private String patientId;
    private Boolean isActive;

    public RadiotherapySuspendedRecords() {
    }

    public RadiotherapySuspendedRecords(long id) {
        this.id = id;
    }

    public RadiotherapySuspendedRecords(long id, Long radiotherapyRecordId, Long startTime, Integer suspendDays, Integer reason, String patientId, Boolean isActive) {
        this.id = id;
        this.radiotherapyRecordId = radiotherapyRecordId;
        this.startTime = startTime;
        this.suspendDays = suspendDays;
        this.reason = reason;
        this.patientId = patientId;
        this.isActive = isActive;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Long getRadiotherapyRecordId() {
        return radiotherapyRecordId;
    }

    public void setRadiotherapyRecordId(Long radiotherapyRecordId) {
        this.radiotherapyRecordId = radiotherapyRecordId;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Integer getSuspendDays() {
        return suspendDays;
    }

    public void setSuspendDays(Integer suspendDays) {
        this.suspendDays = suspendDays;
    }

    public Integer getReason() {
        return reason;
    }

    public void setReason(Integer reason) {
        this.reason = reason;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
