package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RADIOTHERAPY".
 */
public class Radiotherapy implements java.io.Serializable {

    private long id;
    private long startTime;
    private Integer resultType;
    private String patientId;
    private String predictDosage;
    private String currentCount;
    private String weeksCount;
    private String notes;
    private Boolean isActive;

    public Radiotherapy() {
    }

    public Radiotherapy(long id) {
        this.id = id;
    }

    public Radiotherapy(long id, long startTime, Integer resultType, String patientId, String predictDosage, String currentCount, String weeksCount, String notes, Boolean isActive) {
        this.id = id;
        this.startTime = startTime;
        this.resultType = resultType;
        this.patientId = patientId;
        this.predictDosage = predictDosage;
        this.currentCount = currentCount;
        this.weeksCount = weeksCount;
        this.notes = notes;
        this.isActive = isActive;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getStartTime() {
        return startTime;
    }

    public void setStartTime(long startTime) {
        this.startTime = startTime;
    }

    public Integer getResultType() {
        return resultType;
    }

    public void setResultType(Integer resultType) {
        this.resultType = resultType;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getPredictDosage() {
        return predictDosage;
    }

    public void setPredictDosage(String predictDosage) {
        this.predictDosage = predictDosage;
    }

    public String getCurrentCount() {
        return currentCount;
    }

    public void setCurrentCount(String currentCount) {
        this.currentCount = currentCount;
    }

    public String getWeeksCount() {
        return weeksCount;
    }

    public void setWeeksCount(String weeksCount) {
        this.weeksCount = weeksCount;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

}
