package de.greenrobot.dao.attention;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.dao.attention.RecordIndexItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECORD_INDEX_ITEM".
*/
public class RecordIndexItemDao extends AbstractDao<RecordIndexItem, Long> {

    public static final String TABLENAME = "RECORD_INDEX_ITEM";

    /**
     * Properties of entity RecordIndexItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "ID");
        public final static Property PatientId = new Property(1, String.class, "patientId", false, "PATIENT_ID");
        public final static Property HospitalId = new Property(2, Long.class, "hospitalId", false, "HOSPITAL_ID");
        public final static Property Time = new Property(3, long.class, "time", false, "TIME");
        public final static Property HospitalName = new Property(4, String.class, "hospitalName", false, "HOSPITAL_NAME");
        public final static Property Type = new Property(5, long.class, "type", false, "TYPE");
        public final static Property IsActive = new Property(6, boolean.class, "isActive", false, "IS_ACTIVE");
    };


    public RecordIndexItemDao(DaoConfig config) {
        super(config);
    }
    
    public RecordIndexItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECORD_INDEX_ITEM\" (" + //
                "\"ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"PATIENT_ID\" TEXT NOT NULL ," + // 1: patientId
                "\"HOSPITAL_ID\" INTEGER," + // 2: hospitalId
                "\"TIME\" INTEGER NOT NULL ," + // 3: time
                "\"HOSPITAL_NAME\" TEXT," + // 4: hospitalName
                "\"TYPE\" INTEGER NOT NULL ," + // 5: type
                "\"IS_ACTIVE\" INTEGER NOT NULL );"); // 6: isActive
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECORD_INDEX_ITEM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RecordIndexItem entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getPatientId());
 
        Long hospitalId = entity.getHospitalId();
        if (hospitalId != null) {
            stmt.bindLong(3, hospitalId);
        }
        stmt.bindLong(4, entity.getTime());
 
        String hospitalName = entity.getHospitalName();
        if (hospitalName != null) {
            stmt.bindString(5, hospitalName);
        }
        stmt.bindLong(6, entity.getType());
        stmt.bindLong(7, entity.getIsActive() ? 1L: 0L);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RecordIndexItem readEntity(Cursor cursor, int offset) {
        RecordIndexItem entity = new RecordIndexItem( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // patientId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // hospitalId
            cursor.getLong(offset + 3), // time
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // hospitalName
            cursor.getLong(offset + 5), // type
            cursor.getShort(offset + 6) != 0 // isActive
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RecordIndexItem entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setPatientId(cursor.getString(offset + 1));
        entity.setHospitalId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTime(cursor.getLong(offset + 3));
        entity.setHospitalName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.getLong(offset + 5));
        entity.setIsActive(cursor.getShort(offset + 6) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RecordIndexItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RecordIndexItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
