package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECORD_INDEX".
 */
public class RecordIndex implements java.io.Serializable {

    private long id;
    private long indexItemRecordId;
    /** Not-null value. */
    private String patientId;
    /** Not-null value. */
    private String indexName;
    private long indexId;
    private Float normalMin;
    private Float normalMax;
    private long time;
    private int status;
    /** Not-null value. */
    private String value;
    private String unitName;
    private boolean isActive;

    public RecordIndex() {
    }

    public RecordIndex(long id) {
        this.id = id;
    }

    public RecordIndex(long id, long indexItemRecordId, String patientId, String indexName, long indexId, Float normalMin, Float normalMax, long time, int status, String value, String unitName, boolean isActive) {
        this.id = id;
        this.indexItemRecordId = indexItemRecordId;
        this.patientId = patientId;
        this.indexName = indexName;
        this.indexId = indexId;
        this.normalMin = normalMin;
        this.normalMax = normalMax;
        this.time = time;
        this.status = status;
        this.value = value;
        this.unitName = unitName;
        this.isActive = isActive;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getIndexItemRecordId() {
        return indexItemRecordId;
    }

    public void setIndexItemRecordId(long indexItemRecordId) {
        this.indexItemRecordId = indexItemRecordId;
    }

    /** Not-null value. */
    public String getPatientId() {
        return patientId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /** Not-null value. */
    public String getIndexName() {
        return indexName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    public long getIndexId() {
        return indexId;
    }

    public void setIndexId(long indexId) {
        this.indexId = indexId;
    }

    public Float getNormalMin() {
        return normalMin;
    }

    public void setNormalMin(Float normalMin) {
        this.normalMin = normalMin;
    }

    public Float getNormalMax() {
        return normalMax;
    }

    public void setNormalMax(Float normalMax) {
        this.normalMax = normalMax;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    /** Not-null value. */
    public String getValue() {
        return value;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValue(String value) {
        this.value = value;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

}
