package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECORD_INDEX_ITEM".
 */
public class RecordIndexItem implements java.io.Serializable {

    private long id;
    /** Not-null value. */
    private String patientId;
    private Long hospitalId;
    private long time;
    private String hospitalName;
    private long type;
    private boolean isActive;

    public RecordIndexItem() {
    }

    public RecordIndexItem(long id) {
        this.id = id;
    }

    public RecordIndexItem(long id, String patientId, Long hospitalId, long time, String hospitalName, long type, boolean isActive) {
        this.id = id;
        this.patientId = patientId;
        this.hospitalId = hospitalId;
        this.time = time;
        this.hospitalName = hospitalName;
        this.type = type;
        this.isActive = isActive;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPatientId() {
        return patientId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public Long getHospitalId() {
        return hospitalId;
    }

    public void setHospitalId(Long hospitalId) {
        this.hospitalId = hospitalId;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public String getHospitalName() {
        return hospitalName;
    }

    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    public long getType() {
        return type;
    }

    public void setType(long type) {
        this.type = type;
    }

    public boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

}
