package de.greenrobot.dao.attention;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SURGERY_RECORD".
 */
public class SurgeryRecord implements java.io.Serializable {

    private long id;
    private long hospitalId;
    private long therapeuticId;
    private long time;
    private Long hospitalRecordId;
    private String notes;
    private String doctorName;
    private String therapeuticName;
    private String patientId;
    private String hospitalName;
    private boolean isActive;

    public SurgeryRecord() {
    }

    public SurgeryRecord(long id) {
        this.id = id;
    }

    public SurgeryRecord(long id, long hospitalId, long therapeuticId, long time, Long hospitalRecordId, String notes, String doctorName, String therapeuticName, String patientId, String hospitalName, boolean isActive) {
        this.id = id;
        this.hospitalId = hospitalId;
        this.therapeuticId = therapeuticId;
        this.time = time;
        this.hospitalRecordId = hospitalRecordId;
        this.notes = notes;
        this.doctorName = doctorName;
        this.therapeuticName = therapeuticName;
        this.patientId = patientId;
        this.hospitalName = hospitalName;
        this.isActive = isActive;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getHospitalId() {
        return hospitalId;
    }

    public void setHospitalId(long hospitalId) {
        this.hospitalId = hospitalId;
    }

    public long getTherapeuticId() {
        return therapeuticId;
    }

    public void setTherapeuticId(long therapeuticId) {
        this.therapeuticId = therapeuticId;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public Long getHospitalRecordId() {
        return hospitalRecordId;
    }

    public void setHospitalRecordId(Long hospitalRecordId) {
        this.hospitalRecordId = hospitalRecordId;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getDoctorName() {
        return doctorName;
    }

    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    public String getTherapeuticName() {
        return therapeuticName;
    }

    public void setTherapeuticName(String therapeuticName) {
        this.therapeuticName = therapeuticName;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getHospitalName() {
        return hospitalName;
    }

    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    public boolean getIsActive() {
        return isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

}
